version: "3.8"

services:
  web:
    build: .
    container_name: ci4-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always
    networks:
      - ci4-network
  db:
    image: mysql:8.0
    container_name: ci4-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: codeigniter4
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    restart: always
    networks:
      - ci4-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - ci4-network

networks:
  ci4-network:
    driver: bridge
